---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tester
spec:
  selector:
    matchLabels:
      app: tester
  template:
    metadata:
      labels:
        app: tester
    spec:
      containers:
      - name: tester
        image: aryavinayak/tester
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092